id: PBC60C999
initial_creation_type: input
source_metadata:
  title: Lachung Apo Series
  language: bo
  description: 'Texts by the Nyingma master Lachung Apo (bla chung a pho) alias Thupten
    Sherab Gyatso (thub bstan shes rab rgya mtsho, 1905–1975), who was a close friend
    and biographer of Gendün Chöpel:'
  volume:
    c3c30f58ef2146dc84c9ee55ee7f0f48:
      title: 'Aho Ye: Impressions of an Insightful Experience'
      parent: Dzogchen
    d7e72f2272934d8e9d37af7e8d98552c:
      title: 'Wisdom Nexus: A Guru Sādhana'
      parent: Dzogchen
created_at: '2022-03-01T00:32:39.202040'
last_modified_at: '2022-03-01T00:32:39.202043'
statistics:
  total_words: 301
  total_non_words: 31
quality:
  non_words_ratio: 0.1
